# Generated by Django 3.1.4 on 2020-12-31 04:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_to_json',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_image', models.FileField(default='image/default.png', upload_to='image/')),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
