# Generated by Django 3.1.4 on 2020-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201231_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_to_json',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
