# Generated by Django 3.1.4 on 2021-01-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201231_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_to_json',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
